### ISSUE TITLE
NBT Tag too big error

### ISSUE THREAD

**Issue by Reginald-Halifrax** [Spectre0987/TardisMod#215]
I am currently using a Git build (though I don't know if using a release would change anything) and using it in a modpack, multiplayer.

If a player goes through the interior tardis doors about 100% of the time the other players in the tardis get dropped from the server with this this [Error](https://pastebin.com/qJ5WieDw) (This is not a CRASH)

Originally this wasn't too big a deal and you could just reconnect. But now this error is occuring simply existing in the tardis. Softlocking the players.

If further information is needed I'll oblige where I can.

Sorry for the issues!

Edit: forgot to mention this [error](https://pastebin.com/Bcn4QSuE) is also spammed into the console after the player is dropped

**Comment by Suffril** [comment]
We generally don't support builds built from github because as you can probably figure, things would still be in flux and being changed constantly, especially through the past day or so 

I don't think Spectre will be too keen on helping with a non-official build, but I guess I'll try find the issue regardless
I figure it may be something to do with Spectres BOTI changes, but I think he did those on a different branch than master?

So what I need to know, is the following:

What commit did you compile from?
What branch?
What other mods are installed?

**Comment by Reginald-Halifrax** [comment]
Up until now did i notice that 0.0.9b existed so me and my wife put it on the clients and server to see if its fixed, it is fixed now. I am sorry for wasting time with git builds, i do try to avoid it where available but you guys do lovely work, hard to resist!

**Comment by Suffril** [comment]
All good <3
