### ISSUE TITLE
Can this 1.12.2 Artron issues please be fixed.

### ISSUE THREAD

**Issue by josh-65** [Spectre0987/TardisMod#332]
When I have Artron banks in the TARDIS and then reload my game and hit the refuel button it resets to 0 Artron units. And destroying the Artron banks then says the Atron units are -128 x how many Artron banks I have.

If I destroy the Arton banks, then reload, hit the refuel button and then place them back fixes this but I don't want to do this every time I try to play the game.

**Comment by 50ap5ud5** [comment]
Hi there, this issue is a known bug with the mod that will occur for Tardises that were created before the 0.1.3 Artron Update. Newly created Tardises may not have the problem.

Also, I should stress that the mod developers will not be providing anymore bug fixes or new feature updated to the 1.12.2 versions, because they don't have the resources to be managing two vastly different codebases, as well as the lack of time to support the version of Forge it uses (Forge no longer supports 1.12.2 either) . That's why not many people are responding to your issue here.

The 1.14.4 repo is meant for 1.14. 4 issues only. Because of this, and the fact that we don't support 1.12.2 anymore, that is why the mod owner may have shown their frustration when they closed that issue.
