### ISSUE TITLE
Bug. with the entrance to the TARDIS

### ISSUE THREAD

**Issue by Simikiri** [Spectre0987/TardisMod#333]
I go into the TARDIS and I can't do anything, not get out, etc. getting out of the game only helps

**Comment by 50ap5ud5** [comment]
Hi, there's not enough provided information for other people to help you. Please provide information such as, the Forge version you are using, list of mods you have installed, the version of Tardis Mod you installed, a latest log file from .minecraft/logs, a list of steps you took before you encountered the issue.

Also, the 1.12.2 versions of this mod is no longer supported by this mod's developers, because they don't have the resources to maintain this and the 1.14.4 versions. This means they won't provide any bug fixes or new features. Additionally, Forge 1.12.2 is not supported by the Forge team, so the mod developers cannot get help from them either.

Hope this helps
